Traceback (most recent call last):
  File "main.py", line 75, in <module>
    train_loss = train(model, device, train_loader, optimizer, criterion)
TypeError: 'numpy.ndarray' object is not callable
